name: Autograding

on:
  push:
    branches:
      - main

jobs:
  testFruit:
    name: Test Fruit Class
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Gradle
      run: ./gradlew build -x test

    - name: Run Fruit tests
      run: ./gradlew test --tests "com.example.FruitTest"

  testBasket:
    name: Test Basket Class
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
  
      - name: Build with Gradle
        run: ./gradlew build -x test
  
      - name: Run Basket tests
        run: ./gradlew test --tests "com.example.BasketTest"